# Site settings
title: Waldloading
tagline: ein Projekt von Gaby und Gerhard Mayrhofer
description: > # this means to ignore newlines until "baseurl:"
  Waldloading ist ein Projekt der Firmen Mayrhofer EDV, Iktus IT-Audits und May-IT, welches die 
  Aufforstung des vom Borkenkäfer zerstörten Wald in der Koglerau initierte. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://waldloading.at" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass